// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbx_Drk5PErQ8KQhxpZxXII_8zvBLHIAc',
    appId: '1:157932516870:web:508ddf0c33666b7c993587',
    messagingSenderId: '157932516870',
    projectId: 'percobaan6-flutter-project',
    authDomain: 'percobaan6-flutter-project.firebaseapp.com',
    databaseURL: 'https://percobaan6-flutter-project-default-rtdb.firebaseio.com',
    storageBucket: 'percobaan6-flutter-project.firebasestorage.app',
    measurementId: 'G-6ZF4GKZDHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCkbf2K1xJJU2asAPUUOQc5tFaGOSwNcE',
    appId: '1:157932516870:android:368f8ea56bb6a8b8993587',
    messagingSenderId: '157932516870',
    projectId: 'percobaan6-flutter-project',
    databaseURL: 'https://percobaan6-flutter-project-default-rtdb.firebaseio.com',
    storageBucket: 'percobaan6-flutter-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGbxeIgWGqLkwwSFM9993CuOq6YXntt50',
    appId: '1:157932516870:ios:c90bf17605ac032a993587',
    messagingSenderId: '157932516870',
    projectId: 'percobaan6-flutter-project',
    databaseURL: 'https://percobaan6-flutter-project-default-rtdb.firebaseio.com',
    storageBucket: 'percobaan6-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.lunchguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGbxeIgWGqLkwwSFM9993CuOq6YXntt50',
    appId: '1:157932516870:ios:c90bf17605ac032a993587',
    messagingSenderId: '157932516870',
    projectId: 'percobaan6-flutter-project',
    databaseURL: 'https://percobaan6-flutter-project-default-rtdb.firebaseio.com',
    storageBucket: 'percobaan6-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.lunchguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbx_Drk5PErQ8KQhxpZxXII_8zvBLHIAc',
    appId: '1:157932516870:web:6cdb60d02f80110d993587',
    messagingSenderId: '157932516870',
    projectId: 'percobaan6-flutter-project',
    authDomain: 'percobaan6-flutter-project.firebaseapp.com',
    databaseURL: 'https://percobaan6-flutter-project-default-rtdb.firebaseio.com',
    storageBucket: 'percobaan6-flutter-project.firebasestorage.app',
    measurementId: 'G-M2TRTCMEVS',
  );
}
